spring.application.name=store
server.port=8080

# Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5433/store
spring.datasource.username=admin
spring.datasource.password=admin
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA Configuration
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQL82Dialect
spring.jpa.properties.hibernate.format_sql=true

# Liquibase Configuration
spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml

# Logging
logging.level.com.example.store=INFO
logging.level.org.springframework.web=INFO
